### ISSUE TITLE
Export des dossiers des candidats par les membres de commission

### ISSUE THREAD

**Issue by pbellede** [EsupPortail/esup-dematec#11]
Bonjour,

Serait il envisageable de rajouter la possibilité pour les membres de commission de télécharger tous les dossiers des candidats en format Zip comme cela est possible pour les administrateurs.

Merci à vous

**Comment by vbonamy** [comment]
Bonjour,

L'Université de la Rochelle nous a suggéré également cette évolution.

Nous réfléchissons à cette option ; vous trouverez nos premières remarques sur la page suivante : 
https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=345702437#Remarquesetdemandesd'évolution-Lienzippourlesmembres

Si vous voulez bien me donner le nom de votre établissement, je l'ajouterai dans la page donnée ci-dessus ; si un certain nombre d'établissements nous fait remonter la même suggestion, cela nous pousse encore d'avantage à y réfléchir !

On pourrait rendre assez simplement cette fonctionnalité activable (il me parait préférable de la désactiver par défaut) via une case à cocher dans la page des configurations ...

**Comment by vbonamy** [comment]
Le commit 98d408c138cabc2779b0752 ajoute cette possibilité d'export zip pour les membres.
