### ISSUE TITLE
Mot de passe perdu

### ISSUE THREAD

**Issue by AlexSanga** [EsupPortail/esup-dematec#2]
Bonjour Vincent, 
nous reprenons les tests de manière intensive sur cette version, 
et je tombe sur un comportement étrange ...?
La candidature d'un candidat est recevable, j'essaye de me logguer dans Esup Demat avec son email paulvalerydrh1@gmail.com en voulant tester la fonctionnalité "password oublié"
je renseigne l'adresse email ci dessus pour qu'on me renvoie le mot de passe et à la connexion j'ai un message qui semble ne rien avoir à voir "date de cloture des dépots est dépassée .." .
qu'en penses tu ?

**Comment by vbonamy** [comment]
Vu : concernait la date de clôture des dépôts pour un poste donné pour les candidats "auditionnables".
Je clos.

**Comment by AlexSanga** [comment]
bonjour Vincent et merci beaucoup! , 
j'ajoute un complément pour les fonctionnels : à partir du moment ou le dossier est positionné à "auditionnable"  dans le menu "Liste des candidatures" l'accès candidat est coupé.
Il convient donc avant de positionner ce statut de préciser une "date de fin candidat auditionnable" pour le poste concerné (en rapport avec la candidature ci dessus) via le menu "Liste des postes".
A noter l'ajout eventuel d'un commentaire plus parlant que AUTH FAILED dans les statistiques "Authentifications" en cas d'echec de connexion par le candidat
