### ISSUE TITLE
Problème encodage sur l'import des commissions

### ISSUE THREAD

**Issue by pbellede** [EsupPortail/esup-dematec#3]
Index: src/main/java/fr/univrouen/poste/services/CommissionMappingService.java
===================================================================
--- src/main/java/fr/univrouen/poste/services/CommissionMappingService.java	(revision 300)
+++ src/main/java/fr/univrouen/poste/services/CommissionMappingService.java	(working copy)
@@ -30,7 +30,7 @@
 
     private static final String id_nom = "Nom";
 
-    private static final String id_prenom = "PrÃ©nom";
+    private static final String id_prenom = "Prénom";
 
 	public void setAttrFromCell(CommissionEntry commissionEntry, String cellName, String cellValue) {
         if (id_numposte.equals(cellName)) commissionEntry.setNumPoste(cellValue.trim());

**Comment by vbonamy** [comment]
Bonjour,
Je n'ai pas détecté un tel problème.
Le fichier  src/main/java/fr/univrouen/poste/services/CommissionMappingService.java étant en UTF-8, ça ne doit pas poser de problème si votre installation utilise bien UTF-8 de bout en bout. Est-ce bien le cas ?
Merci.
