### ISSUE TITLE
Lorsqu'une personne candidate pour 2 postes le mail est envoyé en double

### ISSUE THREAD

**Issue by pbellede** [EsupPortail/esup-dematec#4]
Bonjour,

Lorsqu'une personne candidate pour 2 postes le mail pour initialiser son identifiant est envoyé 2 fois.

Bien cordialement

**Comment by vbonamy** [comment]
Bonjour,
Lorsqu'une personne candidate pour 1 ou plusieurs postes, 1 premier mail présentant le lien d'activation est envoyé, puis 1 second mail est envoyé pour confirmer la prise en compte de la candidature pour les postes demandés (ce type de dernier mail est ainsi envoyé chaque fois qu'un import résulte d'une nouvelle candidature à des nouveaux postes).
-> il n'y a donc pas 2 mails d'activation mais 1 seul.
Cordialement.
